from typing import Protocol, runtime_checkable


@runtime_checkable
class Queue[T](Protocol):
    def size(self) -> int: ...

    def is_empty(self) -> bool: ...

    def peek(self) -> T: ...

    def enqueue(self, element: T) -> None: ...

    def dequeue(self) -> None: ...
