from typing import Protocol, runtime_checkable


@runtime_checkable
class Stack[T](Protocol):
    def size(self) -> int: ...

    def is_empty(self) -> bool: ...

    def peek(self) -> T: ...

    def push(self, element: T) -> None: ...

    def pop(self) -> None: ...
